name: core
description: Core utilities and services for the Flutter template project including logging and preferences management.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.9.0
  flutter: 3.35.1

resolution: workspace

dependencies:
  firebase_crashlytics: ^4.3.10
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  package_info_plus: ^8.3.1
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.5.3
  slang: ^4.8.1
  slang_flutter: ^4.8.0
  talker: ^4.9.3
  talker_flutter: ^4.9.3

flutter:
  uses-material-design: true
  assets:
    - assets/i18n/

dev_dependencies:
  build_runner: ^2.5.4
  custom_lint: ^0.7.6
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5
  slang_build_runner: ^4.8.0
  yumemi_lints: ^4.2.0

dependency_overrides:
  custom_lint: ^0.7.6
